---
title: Number of morphological slots in spatial forms
author: Alexandra Nogina
date: 'Last update: October 2023'
bibliography: ./data/orig_bib/number_of_morphological_slots_in_spatial_forms.bib
csl: apa.csl
link-citations: true
output:
  html_document:
    number_sections: true
    anchor_sections: true
    pandoc_args: --shift-heading-level-by=-1
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, comment = '')
library(lingglosses)
```

See [data and maps](054_number_of_morphological_slots_in_spatial_forms_map.html).

```{r}
library(RefManageR)
BibOptions(check.entries = FALSE, style = 'text', first.inits = FALSE, bib.style = 'authoryear')
article_citation <- BibEntry(bibtype = 'Incollection', 
 key='nogina2023',
 title='Number of morphological slots in spatial forms',
 author='Alexandra Nogina',
 year='2023',
 editor= 'Daniel, Michael  and Filatov, Konstantin and Maisak, Timur and Moroz, George and Mukhin, Timofey and Naccarato, Chiara and Verhees, Samira',
 publisher='Linguistic Convergence Laboratory, HSE University',
 address='Moscow',
 booktitle= 'Typological Atlas of the Languages of Daghestan (TALD), v 2.0.0',
 url='https://lingconlab.ru/tald',
 doi='10.5281/zenodo.6807070')
```

## {.tabset .tabset-fade .tabset-pills -} 

### Plain text {-}
```{r, results = 'asis'}
print(article_citation, .opts = list(style = 'text'))
```

### BibTeX {-}

```{r}
print(article_citation, .opts = list(style = 'Bibtex'))
```

```{r, child='data/orig_rmd/number_of_morphological_slots_in_spatial_forms.Rmd'}
```



