---
title: Plural marking on imperatives and prohibitives (Maps & Data)
author: Vasiliy Zerzele
date: 'Last update: February 2024'
bibliography: ./data/orig_bib/plural_marking_on_imperatives.bib
csl: apa.csl
link-citations: true
output:
  html_document:
    number_sections: true
    anchor_sections: true
    pandoc_args: --shift-heading-level-by=-1
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, comment = '')
library(lingglosses)
```

See [chapter](057_plural_marking_on_imperatives.html)

```{r}
library(RefManageR)
BibOptions(check.entries = FALSE, style = 'text', first.inits = FALSE, bib.style = 'authoryear')
article_citation <- BibEntry(bibtype = 'Incollection', 
 key='zerzele2023',
 title='Plural marking on imperatives and prohibitives (Maps & Data)',
 author='Vasiliy Zerzele',
 year='2023',
 editor= 'Daniel, Michael  and Filatov, Konstantin and Maisak, Timur and Moroz, George and Mukhin, Timofey and Naccarato, Chiara and Verhees, Samira',
 publisher='Linguistic Convergence Laboratory, NRU HSE',
 address='Moscow',
 booktitle= 'Typological Atlas of the Languages of Daghestan (TALD), v 2.0.0',
 url='http://lingconlab.ru/dagatlas',
 doi='10.5281/zenodo.6807070')
```

## {.tabset .tabset-fade .tabset-pills -} 

### Plain text {-}
```{r, results = 'asis'}
print(article_citation, .opts = list(style = 'text'))
```

### BibTeX {-}

```{r}
print(article_citation, .opts = list(style = 'Bibtex'))
```

```{r, child='data/orig_rmd/plural_marking_on_imperatives_map.Rmd'}
```

```{r, results='asis'}
PrintBibliography(bib)
```

