---
title: "Languages"
link-citations: true
csl: apa.csl
output:
  html_document:
    include:
      in_header: ./html/header_changes.html
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

library(tidyverse)
library(DT)
```


```{r}
map(list.files("data/orig_table", full.names = TRUE), function(file){
  readxl::read_xlsx("data/contributors.xlsx") |> 
    filter(render == 1) |> 
    rowwise() |> 
    mutate(id_0 = sprintf(str_c("%0", nchar(max(id))+1, "d_"), id),
           Chapter = str_c("<a href='",
                                str_c(id_0, filename),
                                ".html'>",
                                title,
                                "</a>")) |> 
    select(filename, Chapter) ->
    features
  
  feature_dataset <- read_tsv(file, show_col_types = FALSE)
  
  feature_dataset |> 
    select(str_which(colnames(feature_dataset), 'value\\d{1,}_name$')) |> 
    pivot_longer(cols = everything()) |> 
    distinct() |>  
    mutate(name = str_remove(name, '_name')) ->
    columns_rename
  
  feature_dataset |> 
    select(lang, idiom, matches("value\\d")) |> 
    select(-matches("numeric")) |> 
    rename_with(function(x){columns_rename$value[match(x, columns_rename$name)]}, matches('value\\d{1,}$')) |> 
    select(-matches("value\\d{1,}\\_name")) |> 
    mutate(across(everything(), as.character)) |> 
    pivot_longer(names_to = "Feature", values_to = "Value", -c(lang:idiom)) |> 
    filter(!is.na(Value)) |> 
    rename(Language=lang, 
           Idiom = idiom) |> 
    mutate(filename = str_remove(file, "data/orig_table/"),
           filename = str_remove(filename, ".tsv$")) |> 
    left_join(features, by = join_by(filename)) |> 
    select(Language, Idiom, Chapter, Feature, Value)
}) |> 
  list_rbind() |> 
  mutate(across(everything(), as.factor)) |> 
  arrange(Idiom, Language) |>  
  DT::datatable(filter = 'top', 
                escape = 4,
                rownames = FALSE,
                options = list(
                  pageLength = 100, 
                  autoWidth = TRUE,
                  dom = 'fltpi'))
```

