---
title: "References"
link-citations: true
csl: apa.csl
output:
  html_document:
    include:
      in_header: ./html/header_references.html
bibliography: "data/bibliography.bib"
---

On this page, we list the references from the datasets. Chapters have their own reference list. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

library(tidyverse)
library(DT)
library(RefManageR)
bib <- ReadBib(file = "data/bibliography.bib") 
```

```{r, include=FALSE}
readxl::read_xlsx("data/biblib.xlsx", sheet = "source type and idiom")  |>
  rowwise() |> 
  mutate(source = str_c('<a href="#ref-', bibtexkey, '">', Cite(bib, bibtexkey), '</a>'),
         language = factor(language),
         idiom = factor(idiom),
         source_type2 = category,
         source_type2 = case_when(source_type2 == "incollection" ~ "chapter",
                                  source_type2 == "phdthesis" ~ "PhD Thesis",
                                  source_type2 == "mastersthesis" ~ "MA Thesis",
                                  source_type2 == "misc" ~ "miscellaneous",
                                  source_type == "dictionary" ~ "dictionary",
                                  source_type == "grammar" ~ "grammar",
                                  TRUE ~ source_type2),
         source_type = source_type2,
         source_type = factor(source_type)) |> 
  select(language, idiom, source, source_type) |> 
  rename(`source type` = source_type) |> 
  DT::datatable(filter = 'top', 
                escape = 4, 
                rownames = FALSE,
                options = list(
                pageLength = 100, 
                autoWidth = TRUE,
                dom = 'fltpi'))
```

```{r, results = "asis"}
str_c(c("---", 
      "nocite: |",
      str_c("  ", str_c("@", names(bib), collapse = ", ")),
      "---"), collapse = "\n") |> 
  cat()
```


## References

