## Introduction {#intro}

Different languages may use different strategies to refer to the days before and after today, and they differ in terms of the number of consecutive days that have a special term. For example,  English has a special word for a day after today, but no special words for days after tomorrow, using a productive and fully compositional construction instead: 'the day after tomorrow', 'the day after the day after tomorrow', etc. Similarly, Russian stacks a prefix meaning 'after' on top of the word for tomorrow, cf. *zavtra* 'tomorrow', *posle-zavtra* 'the day after tomorrow', *posle-posle-zavtra* 'the day after the day after tomorrow', etc. East Caucasian languages are different from English or Russian in this regard, since they typically have more names for days before and after today. Such day’s names can be formed via different strategies (more on than in “days after today”)

## Days before today

For most languages, dictionaries report only one or two terms for the days before today, which does not allow us to detect any strategies of naming the days before today for most languages. But some strategies can still be seen. For example, the Andic languages form terms for the days before today by adding various affixes to ‘yesterday’ (which is a strategy different from the formation of terms for the days after today in these languages). There are also cases where names for the days before and after today are formed in a similar way. For example in Georgian the term for the day after tomorrow may be formed on the basis of the term for tomorrow, and the term for the day before yesterday is formed on the basis of the term for yesterday.However, insufficient data does not allow us to describe the  strategies for all languages. In most East Caucasian languages the system of naming the days after today is much better developed than the system of naming the days before today. It can be seen when comparing [Map1](032_days_after_today_map.html#m1) and [Map3](32_days_after_today_map.html#m3), which contain data on the number of terms for the days after today and before today, respectively. Also [Map3](32_days_after_today_map.html#m3) shows that for the terms before today, the number will not differ for most languages. This is actually quite rare: according to [@tent1998structure: 122], only 12% of languages in the world have such asymmetrical systems. Such a discrepancy between the number of terms for the days after today and the days before today is of interest for a deeper study.
However, the reason for this might be simply the little attention to the days before today by dictionary compilers.

## Days after today

Many East Caucasian languages have a large number of unique terms for days after today. Special terms for up to the fifth day after tomorrow are attested in some languages. In the languages of Daghestan, we found three main strategies to designate days after today among different languages and language families: 1) non-derived terms; 2) semi-compositional terms with similar suffixes (most often locative in origin) but with lexical roots of unclear etymology; 3) transparently compositional constructions. 

The presence of a large number of unique terms for the days after today is typologically quite rare. According to [@tent1998structure: 124], only 7% of languages of the world have a system of naming days after today with a distinct term for more than three days after today. 


## Results

As mentioned in the @intro, there are three main strategies for naming days after today. 

The first strategy involves non-derived terms. This strategy is characterized by the presence of a large number of distinct terms for days after today listed in the dictionary. For example, the dictionary of Bagvalal contains the following forms: *saj* 'the day after tomorrow', *nid* 'on the third day', *čʼĩt’w* 'on the fourth day', *nas’* 'on the fifth day' [@magomedova2004: 309, 275, 402]. These forms usually have nothing in common, so they are clearly not derived from one another. However, this is not always the case. In some cases, different forms share similar elements (usually locative affixes), like *čʼint’u* 'on the fourth day' and *qint’u* 'on the fifth day' in Godoberi [@saidova2006: 320, 191]. This similarity is not enough to attribute this language to the second strategy, especially since the rest of the paradigm in Godoberi is clearly non-derivational.

The second strategy uses identical or similar affixes attached to a base with a usually unclear etymology. Most often, these affixes have evolved from old forms of locatives (complex systems of locative forms are a hallmark of East Caucasian languages.) Usually the meanings of these affixes are hard to pinpoint. In some cases, they lost their locative meaning too long ago and are no longer used in locative contexts. But sometimes we can suppose that the original affix was locative. For example, *-qa* in Tsakhur is an allative affix [@kibrik1999: 55], cf. *qːijqa* ‘tomorrow’, and *čɨqaqana* ‘on the third day’.
The number of distinct terms for days after today in this strategy varies from two to six. An example of a language that uses this strategy is Ingush: *cʼul:a* 'on the third day', *cʼumoaka* 'on the fourth day', *cʼulcʼumoaka* 'on the fifth day' [@kurkiev2005: 478, 815]. According to Johanna Nichols (p.c.), these forms are definitely compositional, but all morphemes are opaque.

The third strategy is the use of transparently compositional constructions. These often involve combinations of the word 'day' (or, more rarely, 'tomorrow') with words that can be translated as 'next', or 'another', or in some cases with numbers. Combinations of a word with an affix meaning 'after' also belong to this category. 

Dictionaries of languages that use this strategy usually contain only a small number of distinct terms for days after today (mostly one or two). Examples of languages with this strategy are the Turkic language Kumyk, cf. *birisigiun* 'the day after tomorrow' (*giun* 'day' and *birisi* 'another') [@bammatov2013: 58], and the East Caucasian language Archi, cf. *os̄ut iqna* 'the day after tomorrow' (*iq* 'day', *os* 'one') [@kibrik1977dict: 375].

Given that it is sometimes impossible to strictly separate the first strategy from the second, and that in one and the same language different strategies can be used for different terms, we decided to classify a language as making use of the compositional/semi-compositional strategy if there are at least two compositional/semi-compositional terms for languages with fewer than four terms in total, and at least three for languages with four or more terms in total.

## Distribution

The first (non-derivational) strategy is very common in Andic languages. It is also found in Avar, as well as in Khinalug and Budukh (Lezgic). For Khinalug and Budukh this is rather unexpected, since these two languages are quite far from the area where the rest of the languages with this strategy are located. The second strategy (compositional) is the most frequent. It is found in Lezgic (Kryz and Tabasaran), Tsezic (Bezhta, Khwarshi and Hunzib), Dargwa, Lak and Nakh languages (with the exception of Tsova-Tush, for which we do not have sufficient data). The third strategy (semi-compositional) is found in Turkic, several Lezgic languages (Agul, Archi and Rutul), and Hinuq of the Tsezic branch. The distribution of these three strategies is shown on [Map 1](032_days_before_and_after_today_map.html#m1).

If we look at the number of distinct terms included in the dictionary, it is interesting to note that further to the east the number of terms decreases (see [Map 2](032_days_before_and_after_today_map.html#m2)). Perhaps this correlates with the introduction of names for the days of the week from Arabic. They are commonly used in the languages of Daghestan, see [@zabitov2001: 111-112], and could make designations beyond the first day after tomorrow redundant. The preservation of old words in the languages of the north could be explained by the fact that Islam and Arabic reached these communities much later and less directly [@shihaliev2007: 4].

As already mentioned, there is a correlation between strategies and number of terms: the first strategy (non-derivational) tends to use a larger number of distinct terms, usually four or five (so such languages can name up to five days since today), more rarely two (but these cases could be due to a lack of data) while the third strategy (compositional) tends to use only a few (usually two and three) terms for the days after today, and both options are possible for the second strategy (from two to seven terms). It should be kept in mind that perhaps not all of the terms recorded in the dictionaries are still in use. See, for example, [@nichols2011: 192] on the use of days before today and after today in Ingush.

## References {-}