## {-}

General chapter: [Phonology](phonology.html)

## Introduction

Among the languages of the world with ejective consonants there exists a tendency for them to lack /p’/ [@greenberg1970: 127; @maddieson1984: 103; via @ohala&solé2008: 332]. In the Nakh-Daghestanian family this too seems to be the case and thus, in this chapter the distribution of ejective /p’/ will be mapped across the languages of the family, as well as across languages outside of Nakh-Daghestanian family that are nevertheless part of the Daghestan linguistic area.

## Results

As mentioned in the introduction, lack of ejective p is found in substantial amount of languages in the region, such as in Andi [@kayeetaldraft2020: 4], Chamalal [@bokarev1949a: 12, 15], Avar [@alekseevataev1997: 35] and others. But it is also attested in languages like Tanty Dargwa [@sumbatovalander2014: 40--41], Kryz [@khalilova2009: 13] and many others. 

It is also important to mention languages in which /p’/ is technically present, but is **marginal**. In Karata, for example, /p’/ is found only in onomatopoeias like p’a (onomatopoeia) [@magomedbekova1971: 14]. Same applies for Avar [@alekseevetal2012: 31] and Kryz [@authier2009: 12].

## Distribution

Among the sampled languages all which are non-Nakh-Daghestanian had no ejective /p’/. This is easily explained by the fact that these languages, with the exception of Georgian, simply don’t have any ejective consonant sets. Same also applies to Udi, which belongs to the Nakh-Daghestanian family and whose ejective consonant set is in fact a set of glottalized stops, which includes /pˀ/ [@schulze2005: 13].

Within the Nakh-Daghestanian family, /p’/ is absent or marginal in 21 languages and dialects sampled (of the 58 languages sampled). Notably /p’/ is present in all Nakh and Dargwa languages. Conversely, in all Andic languages as well as in Avar /p’/ is either absent or marginal, with the exception of Akhvakh. In all other cases the absence of /p’/ does not seem to be distributed genealogically, such as in the case of Khwarshi and Kryz. While for Kryz the reason is uncertain, for Khwarshi it can perhaps be explained areally, as it is surrounded by Andic languages, like Tindi and Bagvalal.

## References {-}
