## {-}

General chapter: [Phonology](phonology.html)

## Introduction

Gemination is a phonetic feature, where a consonant is pronounced for a relatively longer duration of time [@mitterer2018]. This feature is not unique to Daghestan and is relatively common cross-linguistically [@blevins2005]. In the descriptory tradition of Nakh-Daghestanian linguistics, there is an ongoing debate on whether or not ‘strong’ vs ‘weak’ distinction (not the same as ‘fortis-lenis’ distinction) exists and if it is in any way different than simple consonant gemination and if ‘gemination’ is the same as ‘consonant length’ (full debate is summarized in [@isakovxalilov2012: 72--76], at least in regards to Hunzib). Additionally, one may see the status of gemination being treated differently in different grammars. Nakh-Daghestanian tradition often sees gemination as a phonemic feature, so it is often included in the consonant phoneme tables (for example of such a description, see [@magometov1970: 33]), while other descriptions may not view it as such (such as in Azerbaijani description of [@shiralievsevortyan1971: 16, 19]). For the purposes of this chapter, **gemination** is the same as **consonant length** and **weak-strong distinction**. 

## Results and Distribution

Most languages in the sample (38/58) have gemination, while a substantial number don’t.

Unlike some other features of the areal, gemination is not limited to the members of the Nakh-Daghestanian family, as it is also a feature of the turkic languages of the area ([@baskakov1973: 9], [@abdullaevaetal2014: 33--56, 72], [@shiralievsevortyan1971: 16--26]) and Georgian (@hewitt1995: 19, 26). Though curiously, Indo-European languages in the area consistently lack this feature and notably, Tat simplifies geminates in loanwords ([@authier2012: 32]).

Among Nakh-Daghestanian languages, gemination is consistently absent in the Tsezic branch, as well as Khinalug. While Standard Dargwa lacks gemination, all other Dargic languages have it.

When it comes to the Lezgic branch the distribution of this feature is more sporadic. Some of it can be explained genetically, such as gemination being absent in the Southern Samur branch. But Lezgian, Rutul and Udi lack geminates despite being more closely related to languages that don’t, than to each other. This distribution can be explained areally, since Lezgian, Rutul, Udi, Budukh, Kryz and Khinalug are all neighbouring languages on the southern edge of the sprachbund, mostly located on the border of Russia and Azerbaijan. 