## {-}

General chapter: [Phonology](phonology.html)

## Introduction

Labialization is a type of consonantal secondary articulation, where the consonant is pronounced with rounded lips. Labialization is widely attested in Caucasian languages, especially in the Abkhaz-Adyghe family and in Nakh-Daghestanian [@catford1972]. This chapter is aimed to map languages within the Daghestan linguistic area based on whether or not they have phonemic labialization as a feature of their consonant inventories.

## Results

Labialization seems to be rather widespread in the region, present in 37 of 58 languages in the sample.

It is important to mention, that, unfortunately, sometimes scholars do not provide a full list of labialized consonants attested in a language, so it is hard to obtain a complete list. It is worth mentioning that there are several types of labialization:

- /w/-labialization --- this kind of labialization is more or less independent of the main place of articulation. This kind of labialization is typical for velar and uvular fricatives and stops and widely attested in East Caucasian languages;

- /ɥ/-labialization --- this kind of labialization is typical for pharyngeals. It looks like the tongue body is retracted (due to the pharyngeal place of articulation) and raised, which results in a /ɥ/-like sound that is not present in East Caucasian languages;

- /y/-labialization --- this kind of labialization is typical only for post-alveolars found in Abkhaz and Abaza (West Caucasian), but also may be the case in Tabasaran [@kibriketal1982: 7--8; @kibrikkodzasov1990: 337] and Agul [@kibrikkodzasov1990: 338].

All of the types above were not distinguished between each other in the analysis and were all labeled as *labialization*.

## Distribution

All languages with phonemic labialization within the sample are part of the Nakh-Daghestanian family. But not all languages within the family had this feature, as 15 out of the 52 languages lacked it. All Tsezic languages lack labialization with the exception of Hinuq. The origin of this  distribution is most likely genealogical, with proto-Tsez reconstructed as mostly lacking labialization [@starostin1994]. Same applies to Nakh languages. But cannot be applied to others (for example: Avar, Budukh, Khinalug, Tsova-Tush and Udi all lack labials). It cannot also be concretely explained areally, as these languages do not border each other and are usually in proximity to other languages, which do have labialization as a phonemic feature.

## References {-}
