---
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(lingglosses)
library(tidyverse)
```

## Introduction

Different languages may use different strategies to refer to the days after today, and they differ in terms of the number of consecutive days that have a special term. For example,  English has no special words for days after tomorrow but uses a productive and fully compositional construction:  'the day after tomorrow', 'the day after the day after tomorrow', etc. Similarly, Russian stacks a prefix meaning 'after' on top of the word for tomorrow, cf. *zavtra* 'tomorrow', *posle-zavtra* 'the day after tomorrow', *posle-posle-zavtra* 'the day after the day after tomorrow', etc.

Many East Caucasian languages have a large  number of unique terms for days after today. Special terms for the fifth day after tomorrow are attested in some languages. In the eastern Caucasus area, we found three main strategies to designate days after today among different languages and language families: 1) non-derived terms; 2) semi-compositional terms with similar suffixes (most often locative in origin) but with lexical roots of unclear etymology; 3) transparently compositional constructions. 

The presence of a large number of unique terms for the days after today is typologically quite rare. According to [@tent1998structure: 124] only 7% of languages have a system of naming days after today with a distinct term for more than three days after today. The languages studied here have another rare feature: the systems for naming days after today and before today are not symmetrical, which means that there are a different number of terms for the days after today and the days before today. According to [@tent1998structure: 122], only 12% of languages in the world have such asymmetrical systems. In most East Caucasian languages the system of naming the days after today is much better developed than the system of naming the days before today. 

For most languages, the dictionary contains only one or two terms for the days before today, which does not allow us to detect any similar strategies in naming the days before today for every language. Of course, some strategies can be highlighted. For example, the Andic languages form terms for the days before today by adding various affixes to "yesterday" (which is a strategy different from the formation of terms for the days after today). There are also strategies corresponding to the strategies for the days after today. But insufficient data does not allow us to allocate strategies for all languages.
However, such a discrepancy between the number of terms for the days after today and the days before today is of interest for a deeper study. It can be seen when comparing [Map 1](032_days_after_today_map.html#m1) and [Map 2](032_days_after_today_map.html#m2), which contain data on the number of terms for the days after today and before today, respectively. Also [Map 3](033_days_after_today_map.html#m1) shows that for the terms before today, the number will not differ for most languages. 

The aim of this chapter is to describe the three strategies of naming the days after today mentioned above in more detail and to show their distribution across languages in the eastern Caucasus.

## Results

As mentioned in the introduction, there are three main strategies for naming days after today. 
The first strategy involves non-derived terms. This strategy is characterized by the presence of large number of distinct terms for days after today listed in the dictionary. For example, the dictionary of Bagvalal contains the following forms: *saj* 'the day after tomorrow', *nid* 'on the third day', *čʼĩt’w* 'on the fourth day',*nas’* 'on the fifth day' [@magomedova2004: 309, 275, 402]. These forms have nothing in common, so they are clearly not derived from one another. However, this is not always the case. In some cases different forms share similar elements, like *čʼint’u* 'on the fourth day' and *qint’u* 'on the fifth day' in Godoberi [@saidova2006: 320, 191]. This similarity is not enough to attribute this language to the second strategy, especially since the rest of the paradigm in Godoberi is non-derivational.

The second strategy uses identical or similar affixes attached to a base with (usually) an unclear etymology. Most often, these affixes have evolved from old forms of locatives (Complex systems of locative forms are a hallmark of East Caucasian languages.) Usually the meaning of these affixes are hard to pinpoint. In some cases they evolved too long ago and are no longer used outside this context. But sometimes we can suppose that the original affix was locative. For example, *-qa* in Tsakhur is an allative affix [@kibrik1999: 55]. cf. *qːijqa* ‘tomorrow’, and *čɨqaqana* ‘on the third day’.
The number of distinct terms for days after today in this strategy varies from 2 to 6. An example of a language that uses this strategy is Ingush: *cʼul:a* 'on the third day', *cʼumoaka* 'on the fourth day', *cʼulcʼumoaka* 'on the fifth day' [@kurkiev2005: 478, 815]. According to Joanna Nichols, these forms are definitely compositional, but all morphemes are opaque (Joanna Nichols, personal communication).

The third strategy is the use of transparently compositional constructions. These often involve combinations of the word 'day' (or, more rarely, 'tomorrow') with words that can be translated as 'next', or 'another', or in some cases with numbers. Combinations of a word with an affix meaning 'after' also belong to this category.
Dictionaries of languages that use this strategy usually contain only a small number of distinct terms for days after today (mostly one or two).
Examples of languages with this strategy are the Turkic language Kumyk: *birisig’un* 'the day after tomorrow' (*g’un* 'day' and *birisi* 'another') [@bammatov2013: 58]; and the East Caucasian language Archi: *os̄ut iqna* 'the day after tomorrow' (*iq* 'day', *os* 'one') [@kibrik1977dict: 375
However, it is impossible to strictly separate the first strategy from the second, and the distribution into one of the three groups occurs depending on how many non-derivational/compositional/affix including terms (out of all distinct terms in this language) there are in these languages. If there are at least three compositional/affix including terms in a language where there are four or more occurrences in the dictionary of terms naming days after today, or at least two words in a language where there are less than four, the language is recognized as compositional/semi-compositional.

## Distribution

The first strategy is very common in Andic languages. It is also found in Avar, as well as in Khinalug and Budukh. The latter two are unexpected, since these languages are not in the central region where the rest of the languages with this strategy are located. The second strategy is the most frequent. It appears in Lezgic (Kryz and Tabasaran), Tsezic (Bezhta, Khwarshi and Hunzib), Dargwa, Lak and Nakh languages (with the exception of Tsova-Tush, for which insufficient data was available). The third strategy appears in Turkic, several Lezgic languages (Agul, Archi and Rutul), and Hinuq of the Tsezic branch. For the distribution of the strategies see [Map 1](032_days_after_today_map.html#m1).

Also interesting is the distribution of the number of distinct terms included in the dictionary. Further to the east the number of terms decreases (see [Map 2](032_days_after_today_map.html#m2)). Perhaps this correlates with the introduction of names for the days of the week from Arabic. They are commonly used in the languages of Dagestan, see [@zabitov2001: 111-112], and could make designations beyond the first day after tomorrow redundant. The preservation of the old words in the languages of the north could be explained by the fact that Islam, and with it, Arabic, reached these communities much later and less directly [@shihaliev2007: 4].

As was mentioned earlier, the first strategy tends to use a large number of distinct terms (usually four and five, sometimes two, but in these cases it is possible to assume insufficient data), while the third one tends to use only a few (usually two and three), and both options are attested for the second strategy (from two to seven terms). It should be kept in mind that perhaps not all of the terms recorded in the dictionaries are still used currently. See, for example, [@nichols2011: 192] on the use of days before today and after today in Ingush.

## References {-}
