## {-}

General chapter: [Phonology](phonology.html)

Labialization is widely attested in East Caucasian languages. However, there are some languages that have lost this feature (e.g. Budukh [@talibov07]). Unfortunately, sometimes scholars do not provide a full list of labialized consonants attested in a language, so it is hard to obtain a complete list. Following [@catford72] it is worth mentioning that there are several types of labialization: 

* /w/-labialization --- this kind of labialization is more or less independent of the main place of articulation. This kind of labialization is typical for velar and uvular fricatives and stops and widely attested in East Caucasian languages;
* /ɥ/-labialization --- this kind of labialization is typical for pharyngeals. It looks like the tongue body is retracted (due to the pharyngeal place of articulation) and raised, which results in a /ɥ/-like sound that is not present in East Caucasian languages;
* /y/-labialization --- this kind of labialization is typical only for post-alveolars found in Abkhaz and Abaza (West Caucasian), but also may be the case in Tabasaran [@kibrik82: 7--8; @kk90: 337] and Agul [@kk90: 338].

Labialization is lost in Bezhta, Udi, Budukh and Khinalug. Possibly the absence of labialized consonants in Nakh languages results from a reinterpretation by scholars of the *w* as forming part of a diphthong. Georgian probably also has labialized consonants, but those cases are analyzed as a combination of a consonant and *w*.

## References {-}
