
## Introduction
This chapter focuses on several topics in the derivation of numerals in the languages of Daghestan. Most of them have not been studied from a typological perspective, although similar topics have been considered in [@moroz2012] on the material of languages of the Caucasus.

Numeral systems in East Caucasian languages are characterized by several general features. Most of the languages are part vigesimal, part decimal, with different distributions of these patterns of derivation across the family. Numerals from ‘1’ to ‘10’ always have dedicated simple roots, ‘20’ and ‘100’ have simple roots in the majority of languages. The native systems can extend up to 1 000. Roots for ‘thousand’ and larger numerals are borrowings.

Numerals can have special affixes shared by a subset of cardinals (and often numerals of other series). The behavior and possible origins of these markers can differ significantly. Here I define these “**numeral markers**” as morphemes which appear on cardinal numerals when they are used adnominally in a noun phrase. Consider the following example from Archi, where the numeral ‘two’ bears the marker -*‹w›u* (with a class marker slot -*‹w›* inside):

(@) Archi [@mikailov1967: 79]
```{r, echo=FALSE}
gloss_example(transliteration = "q’ʷeˤ-**‹w›u** uš.t:u",
              glosses = "two-**‹I›NUM** brother(I).ABS",
              free_translation = "two brothers"
)
```

In many East Caucasian languages, cardinals do not differ in form in adnominal and headless contexts. (The definition of the notions of “head” or “headedness” are not discussed here.) In other contexts, when cardinals are used independently without a corresponding noun (i.e., they are headless), they bear other suffixes or no suffixes (and thus either way they differ from attributively used cardinals). For example, it is characteristic for Lezgic languages to have class suffixes as numeral markers, but in Agul this suffix is used in headless contexts only and, therefore, I do not consider it a numeral marker in this study. In some languages adnominally used cardinals have separate oblique forms, which are used with a noun in an oblique case. Such forms are not taken into account in this chapter either, which means that problems around inflection are left unattended.

Whether a numeral marker is attached or not depends on the lexeme of the numeral and its structure. In many East Caucasian languages, a numeral marker is present only on the last component of a complex numeral or only on some of its components. In such cases, this data represent final components, unless specified otherwise. The marker is almost always absent in the numeral ‘one’; it is also often not used with larger numerals like ‘hundred’, ‘thousand’, ‘million’, etc. Finally, in some languages it can be absent in some other numerals. Each language can have its own subsets of cardinals which do and do not attach the marker.

The following chapter is the result of the research of cardinal, ordinal, and distributive series of numerals in East Caucasian languages. The main focus is on cardinals as it is presumed that they are the most “basic” series from which all the others are often derived (but never vice versa). The maps show the presence of the numeral marker in different subsets of cardinals and in ordinals, the origins of this marker and the peculiarities of its distribution in complex numerals, special morphological features that are characteristic for certain subsets of cardinals only, means of derivation of distributives, and the distribution of possible roots for ‘hundred’.

Apart from East Caucasian languages, the same data were collected for some of the neighboring languages spoken in Daghestan and adjacent regions: Kumyk, Nogai, and Azerbaijani (Turkic), Judeo-Tat and Armenian (Indo-European) and Georgian (Kartvelian). However, these languages do not show a lot of correspondences with the East Caucasian family in discussed features (in fact, none of them have numeral markers) and thus are not discussed further in this chapter.

## Results
The following minor chapters present an overview of several features of numeral morphology across the East Caucasian family:

(1) Origin of the numeral marker
(2) Regularity of the numeral marker
(3) Presence of the numeral marker in the numeral ‘1’
(4) Presence of the numeral marker in the numerals ‘2’—‘10’
(5) Presence of the numeral marker in the numeral ‘20’
(6) Presence of the numeral marker in the numeral ‘100’
(7) Presence of the numeral marker in the numeral ‘1 000’
(8) Special endings for crowns from 30 to 90
(9) Origin of the ‘ten’ component in crowns
(10) Presence of the numeral marker in complex numerals
(11) Presence of a class suffix in the numeral marker
(12) Presence of the numeral marker in ordinals
(13) Derivation of distributives
(14) Root for ‘hundred’

## Distribution
In general, each branch of the family (Avar-Andic, Tsezic, Dargic, Lak, Lezgic, Nakh) is easily distinguished by several features. The following overview of distinctive features of branches and specific regions is not comprehensive and describes the general trends, leaving out many small exceptions.

Avar-Andic languages, spoken in the northern part of the mountainous Daghestan, have numeral markers which originate in emphatic particles (-*gu*, -*da*). In several features Avar-Andic languages are unique in the family: for example, they regularly derive ‘20’ from numerals ‘2’ and ‘10’, unlike other East Caucasian languages, which use monomorphemic roots for ‘20’.

Avar and Akhvakh stand out among other Avar-Andic languages. Unlike other Andic languages, they use a monomorphemic root for the numeral ‘20’ and use the vigesimal derivation of crowns. Akhvakh is the only Avar-Ando-Tsezic language to have a class suffix in the numeral marker.

Tsezic languages are spoken in a small region to the west of the Avar-Andic area. Sometimes this branch forms a unity, with four or all five of the languages exhibiting the same values of the features. Unlike in Avar-Andic languages, in Tsezic numeral markers are present in non-final positions in complex numerals and are absent in hundreds and thousands. However, they are similar to the Avar-Andic branch in other features: they do not have a class suffix in the numeral marker, the numeral ‘1’ does not have the marker. In some features, though, the languages within the Tsezic branch behave differently, with East Tsezic languages (Hunzib and Bezhta) sometimes distinguishing themselves from others.

Languages of the Lezgic branch are scattered across the southeastern part of the region. They are often in opposition to the Avar-Andic branch in terms of the values of the features. The numeral marker in Lezgic languages consists of a class suffix (which can be petrified, as in Lezgian). This type of marker is usually present in non-final positions in complex numerals and is present in the numeral ‘1’ in most of these languages.

Dargic languages form a relatively homogeneous branch, in which languages / lects usually have the same values of the features. They are spoken in a large area in central Daghestan. Their distinctive peculiarity is the presence of the numeral marker in the numeral ‘100’ but not in other hundreds (e. g. example (@tanty100_200)). Similarly to the Avar-Andic branch, in Dargic languages numeral markers do not have class suffixes, they are not used in non-final positions of complex numerals, and they are not used with the numeral ‘1’. Like many Andic languages, in crowns Dargic languages use special suffixes instead of the general numeral markers.

Lak forms its own branch of the family, and is sometimes united with Dargic. The roots for ‘hundred’ are very similar in Lak and Dargic languages. However, Lak has most in common with Archi, a small Lezgic language, geographically isolated from the rest of the branch. Being in constant contact with Avar and Lak settlements, before the russification in the XXth century many Archi speakers were fluent in these languages [@dobrushina2007: 107]. The influence of Lak is evident in the number of features in which Lak and Archi have the same value. In both languages, the numeral marker is also used as an emphatic particle and includes a class marker. It is used in all the numerals from ‘1’ to the thousands, while it is absent in non-final positions in complex numerals. Some of these features distinguish Archi from other Lezgic languages.

Udi is another Lezgic language which stands out within the branch. It has a simple numeral morphology system, and the numeral markers are lost. In this, it is similar to Khinalug, another isolated language which forms its own branch within the family. Both of them are spoken in Azerbaijan, to the south of Daghestan. Nakh languages also have a simplistic numeral morphology and do not have numeral markers.

Other languages of the region (Kumyk, Nogai, Azerbaijani, Armenian, Judeo-Tat, and Georgian) do not display many common features with the East Caucasian languages. None of them have numeral markers (Georgian final -*i* is the nominative marker).

## List of glosses
`r add_gloss("ABS")` — absolutive; `r add_gloss("I")` — class I; `r add_gloss("NUM")` — numeral marker

## References
